var wms_layers = [];

var format_MunicpiosdaRegio3_0 = new ol.format.GeoJSON();
var features_MunicpiosdaRegio3_0 = format_MunicpiosdaRegio3_0.readFeatures(json_MunicpiosdaRegio3_0, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_MunicpiosdaRegio3_0 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_MunicpiosdaRegio3_0.addFeatures(features_MunicpiosdaRegio3_0);
var lyr_MunicpiosdaRegio3_0 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_MunicpiosdaRegio3_0, 
                style: style_MunicpiosdaRegio3_0,
                popuplayertitle: 'Municípios da Região 3',
                interactive: true,
                title: '<img src="styles/legend/MunicpiosdaRegio3_0.png" /> Municípios da Região 3'
            });
var format_Identificaodetradicionalidade_1 = new ol.format.GeoJSON();
var features_Identificaodetradicionalidade_1 = format_Identificaodetradicionalidade_1.readFeatures(json_Identificaodetradicionalidade_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Identificaodetradicionalidade_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Identificaodetradicionalidade_1.addFeatures(features_Identificaodetradicionalidade_1);
var lyr_Identificaodetradicionalidade_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Identificaodetradicionalidade_1, 
                style: style_Identificaodetradicionalidade_1,
                popuplayertitle: 'Identificação de tradicionalidade',
                interactive: true,
    title: 'Identificação de tradicionalidade<br />\
    <img src="styles/legend/Identificaodetradicionalidade_1_0.png" /> Não<br />\
    <img src="styles/legend/Identificaodetradicionalidade_1_1.png" /> Sim<br />\
    <img src="styles/legend/Identificaodetradicionalidade_1_2.png" /> <br />' });
var format_Populao_2 = new ol.format.GeoJSON();
var features_Populao_2 = format_Populao_2.readFeatures(json_Populao_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Populao_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Populao_2.addFeatures(features_Populao_2);
var lyr_Populao_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Populao_2, 
                style: style_Populao_2,
                popuplayertitle: 'População',
                interactive: true,
    title: 'População<br />\
    <img src="styles/legend/Populao_2_0.png" /> 0 - 100<br />\
    <img src="styles/legend/Populao_2_1.png" /> 100 - 500<br />\
    <img src="styles/legend/Populao_2_2.png" /> 500 - 1.000<br />\
    <img src="styles/legend/Populao_2_3.png" /> 1.000 - 2.000<br />\
    <img src="styles/legend/Populao_2_4.png" /> 2.000 - 3.000<br />' });
var format_Populaocomunidadesnoterritorializadas_3 = new ol.format.GeoJSON();
var features_Populaocomunidadesnoterritorializadas_3 = format_Populaocomunidadesnoterritorializadas_3.readFeatures(json_Populaocomunidadesnoterritorializadas_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Populaocomunidadesnoterritorializadas_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Populaocomunidadesnoterritorializadas_3.addFeatures(features_Populaocomunidadesnoterritorializadas_3);
var lyr_Populaocomunidadesnoterritorializadas_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Populaocomunidadesnoterritorializadas_3, 
                style: style_Populaocomunidadesnoterritorializadas_3,
                popuplayertitle: 'População (comunidades não territorializadas)',
                interactive: true,
    title: 'População (comunidades não territorializadas)<br />\
    <img src="styles/legend/Populaocomunidadesnoterritorializadas_3_0.png" /> 0 - 100<br />\
    <img src="styles/legend/Populaocomunidadesnoterritorializadas_3_1.png" /> 100 - 500<br />\
    <img src="styles/legend/Populaocomunidadesnoterritorializadas_3_2.png" /> 500 - 1.000<br />\
    <img src="styles/legend/Populaocomunidadesnoterritorializadas_3_3.png" /> 1.000 - 2.000<br />\
    <img src="styles/legend/Populaocomunidadesnoterritorializadas_3_4.png" /> 2.000 - 3.000<br />' });
var format_Identificaodetradicionalidadecomunidadesnoterritorializadas_4 = new ol.format.GeoJSON();
var features_Identificaodetradicionalidadecomunidadesnoterritorializadas_4 = format_Identificaodetradicionalidadecomunidadesnoterritorializadas_4.readFeatures(json_Identificaodetradicionalidadecomunidadesnoterritorializadas_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Identificaodetradicionalidadecomunidadesnoterritorializadas_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Identificaodetradicionalidadecomunidadesnoterritorializadas_4.addFeatures(features_Identificaodetradicionalidadecomunidadesnoterritorializadas_4);
var lyr_Identificaodetradicionalidadecomunidadesnoterritorializadas_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Identificaodetradicionalidadecomunidadesnoterritorializadas_4, 
                style: style_Identificaodetradicionalidadecomunidadesnoterritorializadas_4,
                popuplayertitle: 'Identificação de tradicionalidade (comunidades não territorializadas)',
                interactive: true,
    title: 'Identificação de tradicionalidade (comunidades não territorializadas)<br />\
    <img src="styles/legend/Identificaodetradicionalidadecomunidadesnoterritorializadas_4_0.png" /> Não<br />\
    <img src="styles/legend/Identificaodetradicionalidadecomunidadesnoterritorializadas_4_1.png" /> Sim<br />' });
var format_RioParaopeba_5 = new ol.format.GeoJSON();
var features_RioParaopeba_5 = format_RioParaopeba_5.readFeatures(json_RioParaopeba_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_RioParaopeba_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_RioParaopeba_5.addFeatures(features_RioParaopeba_5);
var lyr_RioParaopeba_5 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_RioParaopeba_5, 
                style: style_RioParaopeba_5,
                popuplayertitle: 'Rio Paraopeba',
                interactive: false,
                title: '<img src="styles/legend/RioParaopeba_5.png" /> Rio Paraopeba'
            });

lyr_MunicpiosdaRegio3_0.setVisible(true);lyr_Identificaodetradicionalidade_1.setVisible(true);lyr_Populao_2.setVisible(true);lyr_Populaocomunidadesnoterritorializadas_3.setVisible(true);lyr_Identificaodetradicionalidadecomunidadesnoterritorializadas_4.setVisible(true);lyr_RioParaopeba_5.setVisible(true);
var layersList = [lyr_MunicpiosdaRegio3_0,lyr_Identificaodetradicionalidade_1,lyr_Populao_2,lyr_Populaocomunidadesnoterritorializadas_3,lyr_Identificaodetradicionalidadecomunidadesnoterritorializadas_4,lyr_RioParaopeba_5];
lyr_MunicpiosdaRegio3_0.set('fieldAliases', {'CD_MUN': 'CD_MUN', 'NM_MUN': 'NM_MUN', 'CD_RGI': 'CD_RGI', 'NM_RGI': 'NM_RGI', 'CD_RGINT': 'CD_RGINT', 'NM_RGINT': 'NM_RGINT', 'CD_UF': 'CD_UF', 'NM_UF': 'NM_UF', 'SIGLA_UF': 'SIGLA_UF', 'CD_REGIA': 'CD_REGIA', 'NM_REGIA': 'NM_REGIA', 'SIGLA_RG': 'SIGLA_RG', 'CD_CONCU': 'CD_CONCU', 'NM_CONCU': 'NM_CONCU', 'AREA_KM2': 'AREA_KM2', 'auxiliary_storage_labeling_positionx': 'auxiliary_storage_labeling_positionx', 'auxiliary_storage_labeling_positiony': 'auxiliary_storage_labeling_positiony', 'auxiliary_storage_labeling_lineanchorpercent': 'auxiliary_storage_labeling_lineanchorpercent', 'auxiliary_storage_labeling_lineanchorclipping': 'auxiliary_storage_labeling_lineanchorclipping', 'auxiliary_storage_labeling_lineanchortype': 'auxiliary_storage_labeling_lineanchortype', 'auxiliary_storage_labeling_lineanchortextpoint': 'auxiliary_storage_labeling_lineanchortextpoint', });
lyr_Identificaodetradicionalidade_1.set('fieldAliases', {'Nome_da_Co': 'Nome_da_Co', 'REGIÃO': 'REGIÃO', 'Município': 'Município', 'Comunidade': 'Comunidade', 'LATITUDE_Y': 'LATITUDE_Y', 'LONGITUDE_': 'LONGITUDE_', 'POSSUI_GRU': 'POSSUI_GRU', 'SEGMENTO': 'SEGMENTO', 'ID_C': 'ID_C', 'Area(m)': 'Area(m)', 'ID_C2': 'ID_C2', 'Comunidad2': 'Comunidad2', 'REGIÃO_2': 'REGIÃO_2', 'Município_': 'Município_', 'Comunida_1': 'Comunida_1', 'Segmento_2': 'Segmento_2', 'ID_C_2': 'ID_C_2', '4. Identif': '4. Identif', '4.1 Moment': '4.1 Moment', '4.2 Status': '4.2 Status', '4.3 Segmen': '4.3 Segmen', '5. Energia': '5. Energia', '5.1 Fornec': '5.1 Fornec', '5.2 Quedas': '5.2 Quedas', '6. Água en': '6. Água en', '6.1 Fornec': '6.1 Fornec', '6.2 Qualid': '6.2 Qualid', '7. Saneame': '7. Saneame', '8. Acesso': '8. Acesso', '8.1 Condiç': '8.1 Condiç', '8.2 Qualid': '8.2 Qualid', '9. Transpo': '9. Transpo', '9.1 Transp': '9.1 Transp', '9.2 Transp': '9.2 Transp', '10. Ilumin': '10. Ilumin', '11. Conect': '11. Conect', '11.1 Telef': '11.1 Telef', '11.2 Inter': '11.2 Inter', '12. Situaç': '12. Situaç', '13. Cadeia': '13. Cadeia', '14. Condiç': '14. Condiç', '15. Serviç': '15. Serviç', '16. Distân': '16. Distân', '17. Distân': '17. Distân', '18. Popula': '18. Popula', '19. Usos d': '19. Usos d', '20. Obras': '20. Obras', '21. Sofre': '21. Sofre', '22. Bens m': '22. Bens m', '23. Bens i': '23. Bens i', '24. Ativid': '24. Ativid', '25. Catego': '25. Catego', '26. Presen': '26. Presen', '27. Grupos': '27. Grupos', '28. Grupos': '28. Grupos', '29. Grupos': '29. Grupos', '30. Povos': '30. Povos', 'dist_rompi': 'dist_rompi', 'dist_rio_m': 'dist_rio_m', 'ID': 'ID', 'Data e Hor': 'Data e Hor', 'COD_FORM_E': 'COD_FORM_E', '14.1 Conta': '14.1 Conta', '14.2 Conta': '14.2 Conta', '14.3 Conta': '14.3 Conta', '14.4 Polui': '14.4 Polui', '14.5 Prese': '14.5 Prese', '15.1 Assis': '15.1 Assis', '15.2 Educa': '15.2 Educa', '15.3 Outro': '15.3 Outro', '15.4 Servi': '15.4 Servi', '19.1 Lazer': '19.1 Lazer', '19.2 Traba': '19.2 Traba', '19.3 Consu': '19.3 Consu', '24. Serviç': '24. Serviç', 'pop': 'pop', });
lyr_Populao_2.set('fieldAliases', {'Nome_da_Co': 'Nome_da_Co', 'REGIÃO': 'REGIÃO', 'Município': 'Município', 'Comunidade': 'Comunidade', 'LATITUDE_Y': 'LATITUDE_Y', 'LONGITUDE_': 'LONGITUDE_', 'POSSUI_GRU': 'POSSUI_GRU', 'SEGMENTO': 'SEGMENTO', 'ID_C': 'ID_C', 'Area(m)': 'Area(m)', 'ID_C2': 'ID_C2', 'Comunidad2': 'Comunidad2', 'REGIÃO_2': 'REGIÃO_2', 'Município_': 'Município_', 'Comunida_1': 'Comunida_1', 'Segmento_2': 'Segmento_2', 'ID_C_2': 'ID_C_2', '4. Identif': '4. Identif', '4.1 Moment': '4.1 Moment', '4.2 Status': '4.2 Status', '4.3 Segmen': '4.3 Segmen', '5. Energia': '5. Energia', '5.1 Fornec': '5.1 Fornec', '5.2 Quedas': '5.2 Quedas', '6. Água en': '6. Água en', '6.1 Fornec': '6.1 Fornec', '6.2 Qualid': '6.2 Qualid', '7. Saneame': '7. Saneame', '8. Acesso': '8. Acesso', '8.1 Condiç': '8.1 Condiç', '8.2 Qualid': '8.2 Qualid', '9. Transpo': '9. Transpo', '9.1 Transp': '9.1 Transp', '9.2 Transp': '9.2 Transp', '10. Ilumin': '10. Ilumin', '11. Conect': '11. Conect', '11.1 Telef': '11.1 Telef', '11.2 Inter': '11.2 Inter', '12. Situaç': '12. Situaç', '13. Cadeia': '13. Cadeia', '14. Condiç': '14. Condiç', '15. Serviç': '15. Serviç', '16. Distân': '16. Distân', '17. Distân': '17. Distân', '18. Popula': '18. Popula', '19. Usos d': '19. Usos d', '20. Obras': '20. Obras', '21. Sofre': '21. Sofre', '22. Bens m': '22. Bens m', '23. Bens i': '23. Bens i', '24. Ativid': '24. Ativid', '25. Catego': '25. Catego', '26. Presen': '26. Presen', '27. Grupos': '27. Grupos', '28. Grupos': '28. Grupos', '29. Grupos': '29. Grupos', '30. Povos': '30. Povos', 'dist_rompi': 'dist_rompi', 'dist_rio_m': 'dist_rio_m', 'ID': 'ID', 'Data e Hor': 'Data e Hor', 'COD_FORM_E': 'COD_FORM_E', '14.1 Conta': '14.1 Conta', '14.2 Conta': '14.2 Conta', '14.3 Conta': '14.3 Conta', '14.4 Polui': '14.4 Polui', '14.5 Prese': '14.5 Prese', '15.1 Assis': '15.1 Assis', '15.2 Educa': '15.2 Educa', '15.3 Outro': '15.3 Outro', '15.4 Servi': '15.4 Servi', '19.1 Lazer': '19.1 Lazer', '19.2 Traba': '19.2 Traba', '19.3 Consu': '19.3 Consu', '24. Serviç': '24. Serviç', 'pop': 'pop', });
lyr_Populaocomunidadesnoterritorializadas_3.set('fieldAliases', {'REGIÃO': 'REGIÃO', 'Município': 'Município', 'Comunidade': 'Comunidade', 'LATITUDE_Y': 'LATITUDE_Y', 'LONGITUDE_': 'LONGITUDE_', 'POSSUI_GRU': 'POSSUI_GRU', 'SEGMENTO': 'SEGMENTO', 'ID_C': 'ID_C', 'REGIÃO_2': 'REGIÃO_2', 'Município_': 'Município_', 'Comunida_1': 'Comunida_1', 'Segmento_2': 'Segmento_2', 'ID_C_2': 'ID_C_2', '4. Identif': '4. Identif', '4.1 Moment': '4.1 Moment', '4.2 Status': '4.2 Status', '4.3 Segmen': '4.3 Segmen', '5. Energia': '5. Energia', '5.1 Fornec': '5.1 Fornec', '5.2 Quedas': '5.2 Quedas', '6. Água en': '6. Água en', '6.1 Fornec': '6.1 Fornec', '6.2 Qualid': '6.2 Qualid', '7. Saneame': '7. Saneame', '8. Acesso': '8. Acesso', '8.1 Condiç': '8.1 Condiç', '8.2 Qualid': '8.2 Qualid', '9. Transpo': '9. Transpo', '9.1 Transp': '9.1 Transp', '9.2 Transp': '9.2 Transp', '10. Ilumin': '10. Ilumin', '11. Conect': '11. Conect', '11.1 Telef': '11.1 Telef', '11.2 Inter': '11.2 Inter', '12. Situaç': '12. Situaç', '13. Cadeia': '13. Cadeia', '14. Condiç': '14. Condiç', '15. Serviç': '15. Serviç', '16. Distân': '16. Distân', '17. Distân': '17. Distân', '18. Popula': '18. Popula', '19. Usos d': '19. Usos d', '20. Obras': '20. Obras', '21. Sofre': '21. Sofre', '22. Bens m': '22. Bens m', '23. Bens i': '23. Bens i', '24. Ativid': '24. Ativid', '25. Catego': '25. Catego', '26. Presen': '26. Presen', '27. Grupos': '27. Grupos', '28. Grupos': '28. Grupos', '29. Grupos': '29. Grupos', '30. Povos': '30. Povos', 'dist_rompi': 'dist_rompi', 'dist_rio_m': 'dist_rio_m', 'ID': 'ID', 'Data e Hor': 'Data e Hor', 'COD_FORM_E': 'COD_FORM_E', '14.1 Conta': '14.1 Conta', '14.2 Conta': '14.2 Conta', '14.3 Conta': '14.3 Conta', '14.4 Polui': '14.4 Polui', '14.5 Prese': '14.5 Prese', '15.1 Assis': '15.1 Assis', '15.2 Educa': '15.2 Educa', '15.3 Outro': '15.3 Outro', '15.4 Servi': '15.4 Servi', '19.1 Lazer': '19.1 Lazer', '19.2 Traba': '19.2 Traba', '19.3 Consu': '19.3 Consu', '24. Serviç': '24. Serviç', 'pop': 'pop', });
lyr_Identificaodetradicionalidadecomunidadesnoterritorializadas_4.set('fieldAliases', {'REGIÃO': 'REGIÃO', 'Município': 'Município', 'Comunidade': 'Comunidade', 'LATITUDE_Y': 'LATITUDE_Y', 'LONGITUDE_': 'LONGITUDE_', 'POSSUI_GRU': 'POSSUI_GRU', 'SEGMENTO': 'SEGMENTO', 'ID_C': 'ID_C', 'REGIÃO_2': 'REGIÃO_2', 'Município_': 'Município_', 'Comunida_1': 'Comunida_1', 'Segmento_2': 'Segmento_2', 'ID_C_2': 'ID_C_2', '4. Identif': '4. Identif', '4.1 Moment': '4.1 Moment', '4.2 Status': '4.2 Status', '4.3 Segmen': '4.3 Segmen', '5. Energia': '5. Energia', '5.1 Fornec': '5.1 Fornec', '5.2 Quedas': '5.2 Quedas', '6. Água en': '6. Água en', '6.1 Fornec': '6.1 Fornec', '6.2 Qualid': '6.2 Qualid', '7. Saneame': '7. Saneame', '8. Acesso': '8. Acesso', '8.1 Condiç': '8.1 Condiç', '8.2 Qualid': '8.2 Qualid', '9. Transpo': '9. Transpo', '9.1 Transp': '9.1 Transp', '9.2 Transp': '9.2 Transp', '10. Ilumin': '10. Ilumin', '11. Conect': '11. Conect', '11.1 Telef': '11.1 Telef', '11.2 Inter': '11.2 Inter', '12. Situaç': '12. Situaç', '13. Cadeia': '13. Cadeia', '14. Condiç': '14. Condiç', '15. Serviç': '15. Serviç', '16. Distân': '16. Distân', '17. Distân': '17. Distân', '18. Popula': '18. Popula', '19. Usos d': '19. Usos d', '20. Obras': '20. Obras', '21. Sofre': '21. Sofre', '22. Bens m': '22. Bens m', '23. Bens i': '23. Bens i', '24. Ativid': '24. Ativid', '25. Catego': '25. Catego', '26. Presen': '26. Presen', '27. Grupos': '27. Grupos', '28. Grupos': '28. Grupos', '29. Grupos': '29. Grupos', '30. Povos': '30. Povos', 'dist_rompi': 'dist_rompi', 'dist_rio_m': 'dist_rio_m', 'ID': 'ID', 'Data e Hor': 'Data e Hor', 'COD_FORM_E': 'COD_FORM_E', '14.1 Conta': '14.1 Conta', '14.2 Conta': '14.2 Conta', '14.3 Conta': '14.3 Conta', '14.4 Polui': '14.4 Polui', '14.5 Prese': '14.5 Prese', '15.1 Assis': '15.1 Assis', '15.2 Educa': '15.2 Educa', '15.3 Outro': '15.3 Outro', '15.4 Servi': '15.4 Servi', '19.1 Lazer': '19.1 Lazer', '19.2 Traba': '19.2 Traba', '19.3 Consu': '19.3 Consu', '24. Serviç': '24. Serviç', 'pop': 'pop', });
lyr_RioParaopeba_5.set('fieldAliases', {'Source': 'Source', 'GEOCODIGO': 'GEOCODIGO', 'MUNICIPIO': 'MUNICIPIO', 'UF': 'UF', 'CD_UF': 'CD_UF', 'HIDRO': 'HIDRO', 'AREA_HA': 'AREA_HA', });
lyr_MunicpiosdaRegio3_0.set('fieldImages', {'CD_MUN': 'TextEdit', 'NM_MUN': 'TextEdit', 'CD_RGI': 'TextEdit', 'NM_RGI': 'TextEdit', 'CD_RGINT': 'TextEdit', 'NM_RGINT': 'TextEdit', 'CD_UF': 'TextEdit', 'NM_UF': 'TextEdit', 'SIGLA_UF': 'TextEdit', 'CD_REGIA': 'TextEdit', 'NM_REGIA': 'TextEdit', 'SIGLA_RG': 'TextEdit', 'CD_CONCU': 'TextEdit', 'NM_CONCU': 'TextEdit', 'AREA_KM2': 'TextEdit', 'auxiliary_storage_labeling_positionx': 'Hidden', 'auxiliary_storage_labeling_positiony': 'Hidden', 'auxiliary_storage_labeling_lineanchorpercent': 'TextEdit', 'auxiliary_storage_labeling_lineanchorclipping': 'TextEdit', 'auxiliary_storage_labeling_lineanchortype': 'TextEdit', 'auxiliary_storage_labeling_lineanchortextpoint': 'TextEdit', });
lyr_Identificaodetradicionalidade_1.set('fieldImages', {'Nome_da_Co': 'TextEdit', 'REGIÃO': 'TextEdit', 'Município': 'TextEdit', 'Comunidade': 'TextEdit', 'LATITUDE_Y': 'TextEdit', 'LONGITUDE_': 'TextEdit', 'POSSUI_GRU': 'TextEdit', 'SEGMENTO': 'TextEdit', 'ID_C': 'TextEdit', 'Area(m)': 'TextEdit', 'ID_C2': 'TextEdit', 'Comunidad2': 'TextEdit', 'REGIÃO_2': 'TextEdit', 'Município_': 'TextEdit', 'Comunida_1': 'TextEdit', 'Segmento_2': 'TextEdit', 'ID_C_2': 'TextEdit', '4. Identif': 'TextEdit', '4.1 Moment': 'TextEdit', '4.2 Status': 'TextEdit', '4.3 Segmen': 'TextEdit', '5. Energia': 'TextEdit', '5.1 Fornec': 'TextEdit', '5.2 Quedas': 'TextEdit', '6. Água en': 'TextEdit', '6.1 Fornec': 'TextEdit', '6.2 Qualid': 'TextEdit', '7. Saneame': 'TextEdit', '8. Acesso': 'TextEdit', '8.1 Condiç': 'TextEdit', '8.2 Qualid': 'TextEdit', '9. Transpo': 'TextEdit', '9.1 Transp': 'TextEdit', '9.2 Transp': 'TextEdit', '10. Ilumin': 'TextEdit', '11. Conect': 'TextEdit', '11.1 Telef': 'TextEdit', '11.2 Inter': 'TextEdit', '12. Situaç': 'TextEdit', '13. Cadeia': 'TextEdit', '14. Condiç': 'TextEdit', '15. Serviç': 'TextEdit', '16. Distân': 'TextEdit', '17. Distân': 'TextEdit', '18. Popula': 'TextEdit', '19. Usos d': 'TextEdit', '20. Obras': 'TextEdit', '21. Sofre': 'TextEdit', '22. Bens m': 'TextEdit', '23. Bens i': 'TextEdit', '24. Ativid': 'TextEdit', '25. Catego': 'TextEdit', '26. Presen': 'TextEdit', '27. Grupos': 'TextEdit', '28. Grupos': 'TextEdit', '29. Grupos': 'TextEdit', '30. Povos': 'TextEdit', 'dist_rompi': 'TextEdit', 'dist_rio_m': 'TextEdit', 'ID': 'TextEdit', 'Data e Hor': 'TextEdit', 'COD_FORM_E': 'TextEdit', '14.1 Conta': 'TextEdit', '14.2 Conta': 'TextEdit', '14.3 Conta': 'TextEdit', '14.4 Polui': 'TextEdit', '14.5 Prese': 'TextEdit', '15.1 Assis': 'TextEdit', '15.2 Educa': 'TextEdit', '15.3 Outro': 'TextEdit', '15.4 Servi': 'TextEdit', '19.1 Lazer': 'TextEdit', '19.2 Traba': 'TextEdit', '19.3 Consu': 'TextEdit', '24. Serviç': 'TextEdit', 'pop': 'TextEdit', });
lyr_Populao_2.set('fieldImages', {'Nome_da_Co': 'TextEdit', 'REGIÃO': 'TextEdit', 'Município': 'TextEdit', 'Comunidade': 'TextEdit', 'LATITUDE_Y': 'TextEdit', 'LONGITUDE_': 'TextEdit', 'POSSUI_GRU': 'TextEdit', 'SEGMENTO': 'TextEdit', 'ID_C': 'TextEdit', 'Area(m)': 'TextEdit', 'ID_C2': 'TextEdit', 'Comunidad2': 'TextEdit', 'REGIÃO_2': 'TextEdit', 'Município_': 'TextEdit', 'Comunida_1': 'TextEdit', 'Segmento_2': 'TextEdit', 'ID_C_2': 'TextEdit', '4. Identif': 'TextEdit', '4.1 Moment': 'TextEdit', '4.2 Status': 'TextEdit', '4.3 Segmen': 'TextEdit', '5. Energia': 'TextEdit', '5.1 Fornec': 'TextEdit', '5.2 Quedas': 'TextEdit', '6. Água en': 'TextEdit', '6.1 Fornec': 'TextEdit', '6.2 Qualid': 'TextEdit', '7. Saneame': 'TextEdit', '8. Acesso': 'TextEdit', '8.1 Condiç': 'TextEdit', '8.2 Qualid': 'TextEdit', '9. Transpo': 'TextEdit', '9.1 Transp': 'TextEdit', '9.2 Transp': 'TextEdit', '10. Ilumin': 'TextEdit', '11. Conect': 'TextEdit', '11.1 Telef': 'TextEdit', '11.2 Inter': 'TextEdit', '12. Situaç': 'TextEdit', '13. Cadeia': 'TextEdit', '14. Condiç': 'TextEdit', '15. Serviç': 'TextEdit', '16. Distân': 'TextEdit', '17. Distân': 'TextEdit', '18. Popula': 'TextEdit', '19. Usos d': 'TextEdit', '20. Obras': 'TextEdit', '21. Sofre': 'TextEdit', '22. Bens m': 'TextEdit', '23. Bens i': 'TextEdit', '24. Ativid': 'TextEdit', '25. Catego': 'TextEdit', '26. Presen': 'TextEdit', '27. Grupos': 'TextEdit', '28. Grupos': 'TextEdit', '29. Grupos': 'TextEdit', '30. Povos': 'TextEdit', 'dist_rompi': 'TextEdit', 'dist_rio_m': 'TextEdit', 'ID': 'TextEdit', 'Data e Hor': 'TextEdit', 'COD_FORM_E': 'TextEdit', '14.1 Conta': 'TextEdit', '14.2 Conta': 'TextEdit', '14.3 Conta': 'TextEdit', '14.4 Polui': 'TextEdit', '14.5 Prese': 'TextEdit', '15.1 Assis': 'TextEdit', '15.2 Educa': 'TextEdit', '15.3 Outro': 'TextEdit', '15.4 Servi': 'TextEdit', '19.1 Lazer': 'TextEdit', '19.2 Traba': 'TextEdit', '19.3 Consu': 'TextEdit', '24. Serviç': 'TextEdit', 'pop': 'TextEdit', });
lyr_Populaocomunidadesnoterritorializadas_3.set('fieldImages', {'REGIÃO': 'TextEdit', 'Município': 'TextEdit', 'Comunidade': 'TextEdit', 'LATITUDE_Y': 'TextEdit', 'LONGITUDE_': 'TextEdit', 'POSSUI_GRU': 'TextEdit', 'SEGMENTO': 'TextEdit', 'ID_C': 'TextEdit', 'REGIÃO_2': 'TextEdit', 'Município_': 'TextEdit', 'Comunida_1': 'TextEdit', 'Segmento_2': 'TextEdit', 'ID_C_2': 'TextEdit', '4. Identif': 'TextEdit', '4.1 Moment': 'TextEdit', '4.2 Status': 'TextEdit', '4.3 Segmen': 'TextEdit', '5. Energia': 'TextEdit', '5.1 Fornec': 'TextEdit', '5.2 Quedas': 'TextEdit', '6. Água en': 'TextEdit', '6.1 Fornec': 'TextEdit', '6.2 Qualid': 'TextEdit', '7. Saneame': 'TextEdit', '8. Acesso': 'TextEdit', '8.1 Condiç': 'TextEdit', '8.2 Qualid': 'TextEdit', '9. Transpo': 'TextEdit', '9.1 Transp': 'TextEdit', '9.2 Transp': 'TextEdit', '10. Ilumin': 'TextEdit', '11. Conect': 'TextEdit', '11.1 Telef': 'TextEdit', '11.2 Inter': 'TextEdit', '12. Situaç': 'TextEdit', '13. Cadeia': 'TextEdit', '14. Condiç': 'TextEdit', '15. Serviç': 'TextEdit', '16. Distân': 'TextEdit', '17. Distân': 'TextEdit', '18. Popula': 'TextEdit', '19. Usos d': 'TextEdit', '20. Obras': 'TextEdit', '21. Sofre': 'TextEdit', '22. Bens m': 'TextEdit', '23. Bens i': 'TextEdit', '24. Ativid': 'TextEdit', '25. Catego': 'TextEdit', '26. Presen': 'TextEdit', '27. Grupos': 'TextEdit', '28. Grupos': 'TextEdit', '29. Grupos': 'TextEdit', '30. Povos': 'TextEdit', 'dist_rompi': 'TextEdit', 'dist_rio_m': 'TextEdit', 'ID': 'TextEdit', 'Data e Hor': 'TextEdit', 'COD_FORM_E': 'TextEdit', '14.1 Conta': 'TextEdit', '14.2 Conta': 'TextEdit', '14.3 Conta': 'TextEdit', '14.4 Polui': 'TextEdit', '14.5 Prese': 'TextEdit', '15.1 Assis': 'TextEdit', '15.2 Educa': 'TextEdit', '15.3 Outro': 'TextEdit', '15.4 Servi': 'TextEdit', '19.1 Lazer': 'TextEdit', '19.2 Traba': 'TextEdit', '19.3 Consu': 'TextEdit', '24. Serviç': 'TextEdit', 'pop': 'TextEdit', });
lyr_Identificaodetradicionalidadecomunidadesnoterritorializadas_4.set('fieldImages', {'REGIÃO': 'TextEdit', 'Município': 'TextEdit', 'Comunidade': 'TextEdit', 'LATITUDE_Y': 'TextEdit', 'LONGITUDE_': 'TextEdit', 'POSSUI_GRU': 'TextEdit', 'SEGMENTO': 'TextEdit', 'ID_C': 'TextEdit', 'REGIÃO_2': 'TextEdit', 'Município_': 'TextEdit', 'Comunida_1': 'TextEdit', 'Segmento_2': 'TextEdit', 'ID_C_2': 'TextEdit', '4. Identif': 'TextEdit', '4.1 Moment': 'TextEdit', '4.2 Status': 'TextEdit', '4.3 Segmen': 'TextEdit', '5. Energia': 'TextEdit', '5.1 Fornec': 'TextEdit', '5.2 Quedas': 'TextEdit', '6. Água en': 'TextEdit', '6.1 Fornec': 'TextEdit', '6.2 Qualid': 'TextEdit', '7. Saneame': 'TextEdit', '8. Acesso': 'TextEdit', '8.1 Condiç': 'TextEdit', '8.2 Qualid': 'TextEdit', '9. Transpo': 'TextEdit', '9.1 Transp': 'TextEdit', '9.2 Transp': 'TextEdit', '10. Ilumin': 'TextEdit', '11. Conect': 'TextEdit', '11.1 Telef': 'TextEdit', '11.2 Inter': 'TextEdit', '12. Situaç': 'TextEdit', '13. Cadeia': 'TextEdit', '14. Condiç': 'TextEdit', '15. Serviç': 'TextEdit', '16. Distân': 'TextEdit', '17. Distân': 'TextEdit', '18. Popula': 'TextEdit', '19. Usos d': 'TextEdit', '20. Obras': 'TextEdit', '21. Sofre': 'TextEdit', '22. Bens m': 'TextEdit', '23. Bens i': 'TextEdit', '24. Ativid': 'TextEdit', '25. Catego': 'TextEdit', '26. Presen': 'TextEdit', '27. Grupos': 'TextEdit', '28. Grupos': 'TextEdit', '29. Grupos': 'TextEdit', '30. Povos': 'TextEdit', 'dist_rompi': 'TextEdit', 'dist_rio_m': 'TextEdit', 'ID': 'TextEdit', 'Data e Hor': 'TextEdit', 'COD_FORM_E': 'TextEdit', '14.1 Conta': 'TextEdit', '14.2 Conta': 'TextEdit', '14.3 Conta': 'TextEdit', '14.4 Polui': 'TextEdit', '14.5 Prese': 'TextEdit', '15.1 Assis': 'TextEdit', '15.2 Educa': 'TextEdit', '15.3 Outro': 'TextEdit', '15.4 Servi': 'TextEdit', '19.1 Lazer': 'TextEdit', '19.2 Traba': 'TextEdit', '19.3 Consu': 'TextEdit', '24. Serviç': 'TextEdit', 'pop': 'TextEdit', });
lyr_RioParaopeba_5.set('fieldImages', {'Source': 'TextEdit', 'GEOCODIGO': 'TextEdit', 'MUNICIPIO': 'TextEdit', 'UF': 'TextEdit', 'CD_UF': 'TextEdit', 'HIDRO': 'TextEdit', 'AREA_HA': 'TextEdit', });
lyr_MunicpiosdaRegio3_0.set('fieldLabels', {'CD_MUN': 'hidden field', 'NM_MUN': 'inline label - visible with data', 'CD_RGI': 'hidden field', 'NM_RGI': 'hidden field', 'CD_RGINT': 'hidden field', 'NM_RGINT': 'hidden field', 'CD_UF': 'hidden field', 'NM_UF': 'hidden field', 'SIGLA_UF': 'hidden field', 'CD_REGIA': 'hidden field', 'NM_REGIA': 'hidden field', 'SIGLA_RG': 'hidden field', 'CD_CONCU': 'hidden field', 'NM_CONCU': 'hidden field', 'AREA_KM2': 'hidden field', 'auxiliary_storage_labeling_lineanchorpercent': 'hidden field', 'auxiliary_storage_labeling_lineanchorclipping': 'hidden field', 'auxiliary_storage_labeling_lineanchortype': 'hidden field', 'auxiliary_storage_labeling_lineanchortextpoint': 'hidden field', });
lyr_Identificaodetradicionalidade_1.set('fieldLabels', {'Nome_da_Co': 'no label', 'REGIÃO': 'no label', 'Município': 'inline label - visible with data', 'Comunidade': 'hidden field', 'LATITUDE_Y': 'hidden field', 'LONGITUDE_': 'hidden field', 'POSSUI_GRU': 'hidden field', 'SEGMENTO': 'hidden field', 'ID_C': 'hidden field', 'Area(m)': 'inline label - visible with data', 'ID_C2': 'hidden field', 'Comunidad2': 'hidden field', 'REGIÃO_2': 'hidden field', 'Município_': 'hidden field', 'Comunida_1': 'hidden field', 'Segmento_2': 'hidden field', 'ID_C_2': 'hidden field', '4. Identif': 'inline label - visible with data', '4.1 Moment': 'hidden field', '4.2 Status': 'hidden field', '4.3 Segmen': 'inline label - visible with data', '5. Energia': 'hidden field', '5.1 Fornec': 'hidden field', '5.2 Quedas': 'hidden field', '6. Água en': 'hidden field', '6.1 Fornec': 'hidden field', '6.2 Qualid': 'hidden field', '7. Saneame': 'hidden field', '8. Acesso': 'hidden field', '8.1 Condiç': 'hidden field', '8.2 Qualid': 'hidden field', '9. Transpo': 'hidden field', '9.1 Transp': 'hidden field', '9.2 Transp': 'hidden field', '10. Ilumin': 'hidden field', '11. Conect': 'hidden field', '11.1 Telef': 'hidden field', '11.2 Inter': 'hidden field', '12. Situaç': 'hidden field', '13. Cadeia': 'hidden field', '14. Condiç': 'hidden field', '15. Serviç': 'hidden field', '16. Distân': 'hidden field', '17. Distân': 'hidden field', '18. Popula': 'hidden field', '19. Usos d': 'hidden field', '20. Obras': 'hidden field', '21. Sofre': 'hidden field', '22. Bens m': 'hidden field', '23. Bens i': 'hidden field', '24. Ativid': 'hidden field', '25. Catego': 'hidden field', '26. Presen': 'hidden field', '27. Grupos': 'hidden field', '28. Grupos': 'hidden field', '29. Grupos': 'hidden field', '30. Povos': 'hidden field', 'dist_rompi': 'hidden field', 'dist_rio_m': 'hidden field', 'ID': 'hidden field', 'Data e Hor': 'hidden field', 'COD_FORM_E': 'hidden field', '14.1 Conta': 'hidden field', '14.2 Conta': 'hidden field', '14.3 Conta': 'hidden field', '14.4 Polui': 'hidden field', '14.5 Prese': 'hidden field', '15.1 Assis': 'hidden field', '15.2 Educa': 'hidden field', '15.3 Outro': 'hidden field', '15.4 Servi': 'hidden field', '19.1 Lazer': 'hidden field', '19.2 Traba': 'hidden field', '19.3 Consu': 'hidden field', '24. Serviç': 'hidden field', 'pop': 'hidden field', });
lyr_Populao_2.set('fieldLabels', {'Nome_da_Co': 'no label', 'REGIÃO': 'no label', 'Município': 'inline label - visible with data', 'Comunidade': 'hidden field', 'LATITUDE_Y': 'hidden field', 'LONGITUDE_': 'hidden field', 'POSSUI_GRU': 'hidden field', 'SEGMENTO': 'hidden field', 'ID_C': 'hidden field', 'Area(m)': 'inline label - visible with data', 'ID_C2': 'hidden field', 'Comunidad2': 'hidden field', 'REGIÃO_2': 'hidden field', 'Município_': 'hidden field', 'Comunida_1': 'hidden field', 'Segmento_2': 'hidden field', 'ID_C_2': 'hidden field', '4. Identif': 'hidden field', '4.1 Moment': 'hidden field', '4.2 Status': 'hidden field', '4.3 Segmen': 'hidden field', '5. Energia': 'hidden field', '5.1 Fornec': 'hidden field', '5.2 Quedas': 'hidden field', '6. Água en': 'hidden field', '6.1 Fornec': 'hidden field', '6.2 Qualid': 'hidden field', '7. Saneame': 'hidden field', '8. Acesso': 'hidden field', '8.1 Condiç': 'hidden field', '8.2 Qualid': 'hidden field', '9. Transpo': 'hidden field', '9.1 Transp': 'hidden field', '9.2 Transp': 'hidden field', '10. Ilumin': 'hidden field', '11. Conect': 'hidden field', '11.1 Telef': 'hidden field', '11.2 Inter': 'hidden field', '12. Situaç': 'hidden field', '13. Cadeia': 'hidden field', '14. Condiç': 'hidden field', '15. Serviç': 'hidden field', '16. Distân': 'hidden field', '17. Distân': 'hidden field', '18. Popula': 'hidden field', '19. Usos d': 'hidden field', '20. Obras': 'hidden field', '21. Sofre': 'hidden field', '22. Bens m': 'hidden field', '23. Bens i': 'hidden field', '24. Ativid': 'hidden field', '25. Catego': 'hidden field', '26. Presen': 'hidden field', '27. Grupos': 'hidden field', '28. Grupos': 'hidden field', '29. Grupos': 'hidden field', '30. Povos': 'hidden field', 'dist_rompi': 'hidden field', 'dist_rio_m': 'hidden field', 'ID': 'hidden field', 'Data e Hor': 'hidden field', 'COD_FORM_E': 'hidden field', '14.1 Conta': 'hidden field', '14.2 Conta': 'hidden field', '14.3 Conta': 'hidden field', '14.4 Polui': 'hidden field', '14.5 Prese': 'hidden field', '15.1 Assis': 'hidden field', '15.2 Educa': 'hidden field', '15.3 Outro': 'hidden field', '15.4 Servi': 'hidden field', '19.1 Lazer': 'hidden field', '19.2 Traba': 'hidden field', '19.3 Consu': 'hidden field', '24. Serviç': 'hidden field', 'pop': 'no label', });
lyr_Populaocomunidadesnoterritorializadas_3.set('fieldLabels', {'REGIÃO': 'no label', 'Município': 'inline label - visible with data', 'Comunidade': 'no label', 'LATITUDE_Y': 'hidden field', 'LONGITUDE_': 'hidden field', 'POSSUI_GRU': 'hidden field', 'SEGMENTO': 'hidden field', 'ID_C': 'hidden field', 'REGIÃO_2': 'hidden field', 'Município_': 'hidden field', 'Comunida_1': 'hidden field', 'Segmento_2': 'hidden field', 'ID_C_2': 'hidden field', '4. Identif': 'hidden field', '4.1 Moment': 'hidden field', '4.2 Status': 'hidden field', '4.3 Segmen': 'hidden field', '5. Energia': 'hidden field', '5.1 Fornec': 'hidden field', '5.2 Quedas': 'hidden field', '6. Água en': 'hidden field', '6.1 Fornec': 'hidden field', '6.2 Qualid': 'hidden field', '7. Saneame': 'hidden field', '8. Acesso': 'hidden field', '8.1 Condiç': 'hidden field', '8.2 Qualid': 'hidden field', '9. Transpo': 'hidden field', '9.1 Transp': 'hidden field', '9.2 Transp': 'hidden field', '10. Ilumin': 'hidden field', '11. Conect': 'hidden field', '11.1 Telef': 'hidden field', '11.2 Inter': 'hidden field', '12. Situaç': 'hidden field', '13. Cadeia': 'hidden field', '14. Condiç': 'hidden field', '15. Serviç': 'hidden field', '16. Distân': 'hidden field', '17. Distân': 'hidden field', '18. Popula': 'hidden field', '19. Usos d': 'hidden field', '20. Obras': 'hidden field', '21. Sofre': 'hidden field', '22. Bens m': 'hidden field', '23. Bens i': 'hidden field', '24. Ativid': 'hidden field', '25. Catego': 'hidden field', '26. Presen': 'hidden field', '27. Grupos': 'hidden field', '28. Grupos': 'hidden field', '29. Grupos': 'hidden field', '30. Povos': 'hidden field', 'dist_rompi': 'hidden field', 'dist_rio_m': 'hidden field', 'ID': 'hidden field', 'Data e Hor': 'hidden field', 'COD_FORM_E': 'hidden field', '14.1 Conta': 'hidden field', '14.2 Conta': 'hidden field', '14.3 Conta': 'hidden field', '14.4 Polui': 'hidden field', '14.5 Prese': 'hidden field', '15.1 Assis': 'hidden field', '15.2 Educa': 'hidden field', '15.3 Outro': 'hidden field', '15.4 Servi': 'hidden field', '19.1 Lazer': 'hidden field', '19.2 Traba': 'hidden field', '19.3 Consu': 'hidden field', '24. Serviç': 'hidden field', 'pop': 'no label', });
lyr_Identificaodetradicionalidadecomunidadesnoterritorializadas_4.set('fieldLabels', {'REGIÃO': 'no label', 'Município': 'inline label - visible with data', 'Comunidade': 'no label', 'LATITUDE_Y': 'hidden field', 'LONGITUDE_': 'hidden field', 'POSSUI_GRU': 'hidden field', 'SEGMENTO': 'inline label - visible with data', 'ID_C': 'hidden field', 'REGIÃO_2': 'hidden field', 'Município_': 'hidden field', 'Comunida_1': 'hidden field', 'Segmento_2': 'hidden field', 'ID_C_2': 'hidden field', '4. Identif': 'inline label - visible with data', '4.1 Moment': 'hidden field', '4.2 Status': 'hidden field', '4.3 Segmen': 'inline label - visible with data', '5. Energia': 'hidden field', '5.1 Fornec': 'hidden field', '5.2 Quedas': 'hidden field', '6. Água en': 'hidden field', '6.1 Fornec': 'hidden field', '6.2 Qualid': 'hidden field', '7. Saneame': 'hidden field', '8. Acesso': 'hidden field', '8.1 Condiç': 'hidden field', '8.2 Qualid': 'hidden field', '9. Transpo': 'hidden field', '9.1 Transp': 'hidden field', '9.2 Transp': 'hidden field', '10. Ilumin': 'hidden field', '11. Conect': 'hidden field', '11.1 Telef': 'hidden field', '11.2 Inter': 'hidden field', '12. Situaç': 'hidden field', '13. Cadeia': 'hidden field', '14. Condiç': 'hidden field', '15. Serviç': 'hidden field', '16. Distân': 'hidden field', '17. Distân': 'hidden field', '18. Popula': 'hidden field', '19. Usos d': 'hidden field', '20. Obras': 'hidden field', '21. Sofre': 'hidden field', '22. Bens m': 'hidden field', '23. Bens i': 'hidden field', '24. Ativid': 'hidden field', '25. Catego': 'hidden field', '26. Presen': 'hidden field', '27. Grupos': 'hidden field', '28. Grupos': 'hidden field', '29. Grupos': 'hidden field', '30. Povos': 'hidden field', 'dist_rompi': 'hidden field', 'dist_rio_m': 'hidden field', 'ID': 'hidden field', 'Data e Hor': 'hidden field', 'COD_FORM_E': 'hidden field', '14.1 Conta': 'hidden field', '14.2 Conta': 'hidden field', '14.3 Conta': 'hidden field', '14.4 Polui': 'hidden field', '14.5 Prese': 'hidden field', '15.1 Assis': 'hidden field', '15.2 Educa': 'hidden field', '15.3 Outro': 'hidden field', '15.4 Servi': 'hidden field', '19.1 Lazer': 'hidden field', '19.2 Traba': 'hidden field', '19.3 Consu': 'hidden field', '24. Serviç': 'hidden field', 'pop': 'hidden field', });
lyr_RioParaopeba_5.set('fieldLabels', {'Source': 'hidden field', 'GEOCODIGO': 'hidden field', 'MUNICIPIO': 'hidden field', 'UF': 'hidden field', 'CD_UF': 'hidden field', 'HIDRO': 'hidden field', 'AREA_HA': 'hidden field', });
lyr_RioParaopeba_5.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});